### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by dstockhammer** [apivideo/java-sdk#13]
Adding libraries manually is quite the hassle. Is there any reason this package isn't pushed to Maven Central? 

Thanks!

**Comment by olivierapivideo** [comment]
Hi Daniel,

This SDKs will soon be deprecated. We're working on a revamped API client, generated from the openapi description. A first version has just been released and can be found here: https://github.com/apivideo/java-api-client . It is already published on Maven Central. It is mostly iso-functional to java-sdk.

Given this we won't push java-sdk to Maven Central. 

If you decide to switch to the new client don't hesitate to give us feedback. You'll probably be its first user :).

**Comment by dstockhammer** [comment]
I see, thanks for the reply. We'll switch to that client and report any issues we may find (or not) in the other repo!

Cheers!
