### ISSUE TITLE
Cannot sort/filter videos by dates

### ISSUE THREAD

**Issue by acotiuga** [apivideo/java-sdk#2]
The need would be to get a list of videos published after a given date. The https://github.com/apivideo/java-sdk/blob/master/src/main/java/video/api/java/sdk/domain/QueryParams.java is not helpful for sorting by `publishedAt` property even if https://docs.api.video/5.1/videos/list-videos states that it is possible.

**Comment by apiv-thomas** [comment]
Hello, let me have a look at it today.

**Comment by apiv-thomas** [comment]
@acotiuga it should be fixed in [0.5.2](https://github.com/apivideo/java-sdk/releases/tag/0.5.2). Thank you for reporting this issue.

Let me know if all is good for you.

**Comment by acotiuga** [comment]
@apiv-thomas thank you for fixing this. It works well now.

**Comment by apiv-thomas** [comment]
Great! I'm closing the issue.
