### ISSUE TITLE
Update thumbnail from a timecode is not working

### ISSUE THREAD

**Issue by acotiuga** [apivideo/java-sdk#4]
The path to update a thumbnail from a timecode used in https://github.com/apivideo/java-sdk/blob/master/src/main/java/video/api/java/sdk/infrastructure/unirest/video/UnirestVideoClient.java#L192 is `videos/videoId` while in documentation the expected path is `videos/videoId/thumbnail`.
Is it possible that this de-synchronization to be the cause? Is there another layer that I can't access that does the magic?

Thanks!

**Comment by dougsillars** [comment]
closing, fixed in today's merge.

**Comment by acotiuga** [comment]
Thanks for fixing this :+1:
