### ISSUE TITLE
Integer overflow when uploading files larger than 2147M

### ISSUE THREAD

**Issue by aubincleme** [apivideo/java-sdk#6]
When uploading large files, the `UnirestVideoClient` uses `#uploadMultipleRequests()` insted of `#uploadSingleRequest()` to perform the upload of a video in multiple chunks. 

The choice of going through one request or multiple requests is done in https://github.com/apivideo/java-sdk/blob/6fbd1ce31cd00d1a3848c43df7f053421eea07fa/src/main/java/video/api/java/sdk/infrastructure/unirest/video/UnirestVideoClient.java#L120 ; which will check the size of the video file against a fixed size. The size of the video file is taken from https://github.com/apivideo/java-sdk/blob/6fbd1ce31cd00d1a3848c43df7f053421eea07fa/src/main/java/video/api/java/sdk/infrastructure/unirest/video/UnirestVideoClient.java#L105.

However, `File#length()` returns a long, as the size is given in bytes, and can be larger than MAX_INT. When trying to upload a file with a size larger than ~2147M, an integer overflow occurs which will lead to the sdk trying to upload the file in a single request.

**Comment by dougsillars** [comment]
closing, fixed in today's merge. Converted file length into a Biginteger, so we should be ok now :)
