### ISSUE TITLE
File descriptors used for upload are not released when the upload is done

### ISSUE THREAD

**Issue by aubincleme** [apivideo/java-sdk#8]
The `randomAccessFile` define here https://github.com/apivideo/java-sdk/blob/6fbd1ce31cd00d1a3848c43df7f053421eea07fa/src/main/java/video/api/java/sdk/infrastructure/unirest/video/UnirestVideoClient.java#L134 as well as the `chunkFile` defined here https://github.com/apivideo/java-sdk/blob/6fbd1ce31cd00d1a3848c43df7f053421eea07fa/src/main/java/video/api/java/sdk/infrastructure/unirest/video/UnirestVideoClient.java#L152 are never closed.

In practice, it means that there will still exist a file descriptor declared for these files at the system level until the JVM finishes, even if the files are deleted. Some systems (in my case GNU/Linux) won't consider the disk space of a deleted file as freed until there's no more existing descriptors for this file. As a consequence, when using the java-sdk on a GNU/Linux server in a Java web application, the storage space of the server increases linearly as videos get uploaded.

**Comment by olivierapivideo** [comment]
Hi Clément,

Thanks for your feedback and sorry for the late response.

The problem you mentioned was indeed problematic, it has been fixed in release [0.5.5](https://github.com/apivideo/java-sdk/releases/tag/0.5.5) (2020-10-13).

Please let my know if I can close the issue :)

**Comment by aubincleme** [comment]
Sure, thank you for the help !
