### ISSUE TITLE
VideoClient#updateThumbnail() is not working

### ISSUE THREAD

**Issue by aubincleme** [apivideo/java-sdk#9]
The default implementation of the `VideoClient`, `UnirestVideoClient` is not usin the proper endpoint for updating the thumbnail of a video based on a timecode. 

The client is using the route /video/videoId to set the thumbnail

https://github.com/apivideo/java-sdk/blob/6fbd1ce31cd00d1a3848c43df7f053421eea07fa/src/main/java/video/api/java/sdk/infrastructure/unirest/video/UnirestVideoClient.java#L194

However, the documentation of api.video states that the route `/video/videoId/thumbnail` should be used instead, see https://docs.api.video/reference#patch_videos-videoid-thumbnail.

**Comment by olivierapivideo** [comment]
Hi Clément,

Thanks for you feedback.

This one too should have been fixed in the release [0.5.5](https://github.com/apivideo/java-sdk/releases/tag/0.5.5)

**Comment by aubincleme** [comment]
Thanks !
